export const AUDIT_ACTION = {
    USER_REGISTERED: "USER_REGISTERED",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    EMAIL_VERIFIED: "EMAIL_VERIFIED",

    WORKSPACE_CREATED: "WORKSPACE_CREATED",

    URL_CREATED: "URL_CREATED",
    URL_UPDATED: "URL_UPDATED",
    URL_DELETED: "URL_DELETED",
} as const;

export const AUDIT_RESOURCE = {
    ADMIN: "ADMIN",
    USER: "USER",
    WORKSPACE: "WORKSPACE",
    URL: "URL",
} as const;