export const AUDIT_ACTION = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
  USER_AVATAR_UPDATED: 'USER_AVATAR_UPDATED',
  USER_ACCOUNT_DELETED: 'USER_ACCOUNT_DELETED',

  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  VERIFICATION_EMAIL_RESENT: 'VERIFICATION_EMAIL_RESENT',

  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',

  GOOGLE_LOGIN: 'GOOGLE_LOGIN',

  WORKSPACE_CREATED: 'WORKSPACE_CREATED',
  WORKSPACE_UPDATED: 'WORKSPACE_UPDATED',
  WORKSPACE_DELETED: 'WORKSPACE_DELETED',

  URL_CREATED: 'URL_CREATED',
  URL_UPDATED: 'URL_UPDATED',
  URL_DELETED: 'URL_DELETED',

  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',

  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_SESSION_REVOKED_ALL: 'AUTH_SESSION_REVOKED_ALL',

  WORKSPACE_INVITATION_CREATED: 'WORKSPACE_INVITATION_CREATED',
  WORKSPACE_INVITATION_ACCEPTED: 'WORKSPACE_INVITATION_ACCEPTED',
  WORKSPACE_INVITATION_REJECTED: 'WORKSPACE_INVITATION_REJECTED',
  WORKSPACE_INVITATION_REVOKED: 'WORKSPACE_INVITATION_REVOKED',
  WORKSPACE_INVITATION_EXPIRED: 'WORKSPACE_INVITATION_EXPIRED',
} as const;

export const AUDIT_RESOURCE = {
  ADMIN: 'ADMIN',
  USER: 'USER',
  WORKSPACE: 'WORKSPACE',
  URL: 'URL',
  WORKSPACE_INVITATION: 'WORKSPACE_INVITATION',
} as const;