import nodemailer, { type Transporter } from 'nodemailer';

import type {
  MailService,
  SendAcceptanceEmailToInviter,
  SendAcceptanceEmailToInvitee,
  SendResetPasswordEmail,
  SendUrlExpirationReminder,
  SendVerificationEmail,
  SendWorkspaceInvitationEmail,
  UserActionTemplateProps,
} from '../interfaces/mail.service.ts';

import { config } from '../../../config/env/index.ts';

import { verifyEmailTemplate } from '../templates/verify-email.template.ts';
import { resetPasswordTemplate } from '../templates/reset-password.template.ts';
import { userActionTemplate } from '../templates/user-action.template.ts';
import { workspaceInvitationTemplate } from '../templates/workspace-invitation.template.ts';
import { workspaceInvitationAcceptedOwnerTemplate } from '../templates/workspace-invitation-accept-owner.template.ts';

/**
 * SmtpProvider is an implementation of the MailService interface that uses SMTP to send emails.
 */
export class SmtpProvider implements MailService {

  // The transporter is responsible for sending emails using the SMTP protocol. It is initialized in the constructor with the necessary configuration.
  private readonly transporter: Transporter;

  // The 'from' property defines the sender's email address that will be used in all outgoing emails. It is formatted with a display name ("LinkFlow") and the configured SMTP_FROM address.
  private readonly from = `"LinkFlow" <${config.SMTP_FROM}>`;

  // The constructor initializes the SmtpProvider with the necessary SMTP configuration, including host, port, security settings, and authentication credentials.
  constructor() {
    this.transporter = nodemailer.createTransport({
      host: config.SMTP_HOST, // The SMTP server host address, retrieved from the configuration.
      port: Number(config.SMTP_PORT), // The SMTP server port, converted to a number from the configuration.
      secure: config.SMTP_SECURE === 'true', // A boolean indicating whether to use a secure connection (true for port 465, false for other ports), based on the configuration.

      auth: {
        user: config.SMTP_FROM, // The username for SMTP authentication, typically the email address used to send emails, retrieved from the configuration.
        pass: config.SMTP_PASSWORD, // The password for SMTP authentication, retrieved from the configuration.
      },
    });
  }

  /**
   * Sends a verification email to the specified recipient.
   * @param data - An object containing the recipient's email, full name, and verification token.
   */
  async sendVerificationEmail(data: SendVerificationEmail): Promise<void> {

    // Construct the verification URL using the client URL and the verification token provided in the data.
    const verifyUrl = `${config.CLIENT_URL}/verify-email?token=${data.verifyToken}`;

    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the verifyEmailTemplate function.
    await this.sendMail(data.email, 'Verify your email', verifyEmailTemplate(data.fullName, verifyUrl));
  }

  /**
   * Sends a reset password email to the specified recipient.
   * @param data - An object containing the recipient's email, full name, and reset token.
   */
  async sendResetPasswordEmail(data: SendResetPasswordEmail): Promise<void> {

    // Construct the reset password URL using the client URL and the reset token provided in the data.
    const resetUrl = `${config.CLIENT_URL}/reset-password?token=${data.resetToken}`;

    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the resetPasswordTemplate function.
    await this.sendMail(data.email, 'Reset your password', resetPasswordTemplate({
      fullName: data.fullName,

      resetUrl,
    }),
    );
  }

  /**
   * Sends a workspace invitation email to the specified recipient.
   * @param data - An object containing the workspace ID, recipient's name, email, inviter's name, workspace name, invite token, and role name.
   */
  async sendWorkspaceInvitationEmail(data: SendWorkspaceInvitationEmail): Promise<void> {

    // Construct the invitation URL using the client URL, workspace ID, and invite token provided in the data.
    const invitationUrl = `${config.CLIENT_URL}/workspaces/${data.workspaceId}/invitations/accept?token=${data.inviteToken}`;

    // Use the sendMail method to send the email with the specified parameters, including the sender's address, recipient's address, subject, and HTML content generated by the workspaceInvitationTemplate function.
    await this.sendMail(data.email, `You're invited to join ${data.workspaceName}`, workspaceInvitationTemplate(
      data.name, // The name of the recipient, used in the email template to personalize the message.
      data.inviterName, // The name of the inviter, used in the email template to inform the recipient who sent the invitation.
      data.workspaceName, // The name of the workspace, used in the email template to inform the recipient about the workspace they are being invited to.
      data.roleName, // The name of the role assigned to the recipient in the workspace, used in the email template to inform them about their role.
      invitationUrl // The URL that the recipient can click to accept the invitation, constructed using the client URL, workspace ID, and invite token.
    ));
  }

  async sendUrlExpirationReminder(data: SendUrlExpirationReminder): Promise<void> {
    console.log(data);

    // TODO
  }

  /**
   * Sends an acceptance email to the inviter when the invitee accepts the invitation.
   * @param data - An object containing the workspace ID, recipient's name, email, inviter's name, invitee's name, workspace name, invite token, and role name.
   */
  async sendAcceptanceEmailToInviter(data: SendAcceptanceEmailToInviter): Promise<void> {
    
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the workspaceInvitationAcceptedOwnerTemplate function.
    this.sendMail(
      data.email,
      `${data.inviteeName} has accepted the invitation to ${data.workspaceName}`, workspaceInvitationAcceptedOwnerTemplate(
        data.inviterName, // The name of the inviter, used in the email template to personalize the message and inform them about the acceptance.
        data.inviteeName, // The name of the invitee, used in the email template to inform the inviter about who accepted the invitation.
        data.workspaceName, // The name of the workspace, used in the email template to inform the inviter about which workspace the invitation was accepted for.
      ),
    );
  }

  /**
   * Sends an acceptance email to the invitee when they accept the invitation.
   * @param data - An object containing the workspace ID, recipient's name, email, inviter's name, invitee's name, workspace name, invite token, and role name.
   */
  async sendAcceptanceEmailToInvitee(data: SendAcceptanceEmailToInvitee): Promise<void> {
    
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the workspaceInvitationAcceptedOwnerTemplate function.
    await this.sendMail(
      data.email,
      `You have accepted the invitation to ${data.workspaceName}`,
      workspaceInvitationAcceptedOwnerTemplate(
        data.inviterName, // The name of the inviter, used in the email template to inform the invitee about who sent the invitation they accepted.
        data.inviteeName, // The name of the invitee, used in the email template to personalize the message and confirm their acceptance of the invitation.
        data.workspaceName, // The name of the workspace, used in the email template to inform the invitee about which workspace they have accepted the invitation for.
      ),
    );
  }

  /**
   * Sends a user action email to the specified recipient, informing them about an action taken on their account.
   * @param data - An object containing the recipient's email, full name, action description, optional reason, and action time.
   */
  async sendUserActionEmail(data: UserActionTemplateProps): Promise<void> {
    
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the userActionTemplate function.
    await this.sendMail(
      data.email,
      `Your LinkFlow account has been updated: ${data.action}`,
      userActionTemplate(data), // The userActionTemplate function generates the HTML content of the email based on the provided data, including the recipient's full name, action description, optional reason, and action time.
    );
  }

  /**
   * Sends an email using the configured SMTP transporter.
   * @param to - The recipient's email address.
   * @param subject - The subject of the email.
   * @param html - The HTML content of the email.
   */
  private async sendMail(
    to: string,
    subject: string,
    html: string,
  ) {
    // Use the transporter to send the email with the specified parameters, including the sender's address, recipient's address, subject, and HTML content.
    await this.transporter.sendMail({
      from: this.from, // The sender's email address, formatted with a display name and the configured SMTP_FROM address.
      to, // The recipient's email address, provided as a parameter to the sendMail method.
      subject, // The subject line of the email, provided as a parameter to the sendMail method.
      html, // The HTML content of the email, provided as a parameter to the sendMail method.
    });
  }
}
