import nodemailer, { type Transporter } from 'nodemailer';

import type {
  MailService,
  SendAcceptanceEmailToInviter,
  SendAcceptanceEmailToInvitee,
  SendResetPasswordEmail,
  SendUrlExpirationReminder,
  SendVerificationEmail,
  SendWorkspaceInvitationEmail,
  UserActionTemplateProps,
  SendRejectionEmailToInviter,
  SendRevocationEmailToInvitee,
  SendOwnershipTransferredToNewOwner,
  SendOwnershipTransferredToPreviousOwner,
  SendWorkspaceMemberRoleUpdatedEmail,
  SendWelcomeEmail,
  WorkspaceMemberLeaveMail,
  WorkspaceMemberRemovedMail,
  WorkspaceDeletedMail,
} from '../interfaces/mail.service.ts';

import { config } from '../../../config/env/index.ts';

import {
  verifyEmailTemplate,
  resetPasswordTemplate,
  userActionTemplate,
  workspaceInvitationTemplate,
  workspaceInvitationAcceptedOwnerTemplate,
  workspaceInvitationRejectedInviterTemplate,
  workspaceInvitationRevokedInviteeTemplate,
  workspaceOwnershipTransferredNewOwnerTemplate,
  workspaceOwnershipTransferredPreviousOwnerTemplate,
  workspaceInvitationAcceptedInviteeTemplate,
  workspaceMemberRoleUpdatedTemplate,
  welcomeEmailTemplate,
  workspaceMemberLeftOwnerTemplate,
  workspaceMemberRemovedTemplate,
  workspaceDeletedTemplate,
} from '../templates/index.ts';
/**
 * SmtpProvider is an implementation of the MailService interface that uses SMTP to send emails.
 */
export class SmtpProvider implements MailService {
  // The transporter is responsible for sending emails using the SMTP protocol. It is initialized in the constructor with the necessary configuration.
  private readonly transporter: Transporter;

  // The 'from' property defines the sender's email address that will be used in all outgoing emails. It is formatted with a display name ("LinkFlow") and the configured SMTP_FROM address.
  private readonly from = `"LinkFlow" <${config.SMTP_FROM}>`;

  // The constructor initializes the SmtpProvider with the necessary SMTP configuration, including host, port, security settings, and authentication credentials.
  constructor() {
    this.transporter = nodemailer.createTransport({
      host: config.SMTP_HOST, // The SMTP server host address, retrieved from the configuration.
      port: Number(config.SMTP_PORT), // The SMTP server port, converted to a number from the configuration.
      secure: config.SMTP_SECURE === 'true', // A boolean indicating whether to use a secure connection (true for port 465, false for other ports), based on the configuration.

      auth: {
        user: config.SMTP_FROM, // The username for SMTP authentication, typically the email address used to send emails, retrieved from the configuration.
        pass: config.SMTP_PASSWORD, // The password for SMTP authentication, retrieved from the configuration.
      },
    });
  }

  /**
   * Sends an email using the configured SMTP transporter.
   * @param data - An object containing the recipient's email address, subject, and HTML content of the email.
   */
  sendWelcomeEmail(data: SendWelcomeEmail): Promise<void> {
    const dashboardUrl = `${config.CLIENT_URL}/dashboard`;

    return this.sendMail(
      data.email,
      'Welcome to LinkFlow!',
      welcomeEmailTemplate(data.fullName, dashboardUrl),
    );
  }

  /**
   * Sends a verification email to the specified recipient.
   * @param data - An object containing the recipient's email, full name, and verification token.
   */
  async sendVerificationEmail(data: SendVerificationEmail): Promise<void> {
    // Construct the verification URL using the client URL and the verification token provided in the data.
    const verifyUrl = `${config.CLIENT_URL}/verify-email?token=${data.verifyToken}`;

    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the verifyEmailTemplate function.
    await this.sendMail(
      data.email,
      'Verify your email',
      verifyEmailTemplate(data.fullName, verifyUrl),
    );
  }

  /**
   * Sends a reset password email to the specified recipient.
   * @param data - An object containing the recipient's email, full name, and reset token.
   */
  async sendResetPasswordEmail(data: SendResetPasswordEmail): Promise<void> {
    // Construct the reset password URL using the client URL and the reset token provided in the data.
    const resetUrl = `${config.CLIENT_URL}/reset-password?token=${data.resetToken}`;

    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the resetPasswordTemplate function.
    await this.sendMail(
      data.email,
      'Reset your password',
      resetPasswordTemplate({
        fullName: data.fullName,

        resetUrl,
      }),
    );
  }

  /**
   * Sends a workspace invitation email to the specified recipient.
   * @param data - An object containing the workspace ID, recipient's name, email, inviter's name, workspace name, invite token, and role name.
   */
  async sendWorkspaceInvitationEmail(data: SendWorkspaceInvitationEmail): Promise<void> {
    // Construct the invitation URL using the client URL, workspace ID, and invite token provided in the data.
    const invitationUrl = `${config.CLIENT_URL}/dashboard/w/${data.slug}/settings/invitations/accept?token=${data.inviteToken}&workspaceId=${data.workspaceId}&invitationId=${data.invitationId}&slug=${data.slug}`;
    const declineUrl = `${config.CLIENT_URL}/dashboard/w/${data.slug}/settings/invitations/decline?token=${data.inviteToken}&workspaceId=${data.workspaceId}&invitationId=${data.invitationId}&slug=${data.slug}`;
    // Use the sendMail method to send the email with the specified parameters, including the sender's address, recipient's address, subject, and HTML content generated by the workspaceInvitationTemplate function.
    await this.sendMail(
      data.email,
      `You're invited to join ${data.workspaceName}`,
      workspaceInvitationTemplate(
        data.name, // The name of the recipient, used in the email template to personalize the message.
        data.inviterName, // The name of the inviter, used in the email template to inform the recipient who sent the invitation.
        data.workspaceName, // The name of the workspace, used in the email template to inform the recipient about the workspace they are being invited to.
        data.roleName, // The name of the role assigned to the recipient in the workspace, used in the email template to inform them about their role.
        invitationUrl, // The URL that the recipient can click to accept the invitation, constructed using the client URL, workspace ID, and invite token.
        declineUrl, // The URL that the recipient can click to decline the invitation, constructed using the client URL, workspace ID, and invite token.
      ),
    );
  }

  async sendUrlExpirationReminder(data: SendUrlExpirationReminder): Promise<void> {
    console.log(data);

    // TODO
  }

  /**
   * Sends an acceptance email to the inviter when the invitee accepts the invitation.
   * @param data - An object containing the workspace ID, recipient's name, email, inviter's name, invitee's name, workspace name, invite token, and role name.
   */
  async sendAcceptanceEmailToInviter(data: SendAcceptanceEmailToInviter): Promise<void> {
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the workspaceInvitationAcceptedOwnerTemplate function.
    this.sendMail(
      data.email,
      `${data.inviteeName} has accepted the invitation to ${data.workspaceName}`,
      workspaceInvitationAcceptedOwnerTemplate(
        data.inviterName, // The name of the inviter, used in the email template to personalize the message and inform them about the acceptance.
        data.inviteeName, // The name of the invitee, used in the email template to inform the inviter about who accepted the invitation.
        data.workspaceName, // The name of the workspace, used in the email template to inform the inviter about which workspace the invitation was accepted for.
      ),
    );
  }

  /**
   * Sends an acceptance email to the invitee when they accept the invitation.
   * @param data - An object containing the workspace ID, recipient's name, email, inviter's name, invitee's name, workspace name, invite token, and role name.
   */
  async sendAcceptanceEmailToInvitee(data: SendAcceptanceEmailToInvitee): Promise<void> {
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the workspaceInvitationAcceptedOwnerTemplate function.
    await this.sendMail(
      data.email,
      `You have accepted the invitation to ${data.workspaceName}`,
      workspaceInvitationAcceptedInviteeTemplate(
        data.inviteeName, // The name of the inviter, used in the email template to inform the invitee about who sent the invitation they accepted.
        data.workspaceName, // The name of the invitee, used in the email template to personalize the message and confirm their acceptance of the invitation.
        data.roleName, // The name of the workspace, used in the email template to inform the invitee about which workspace they have accepted the invitation for.
      ),
    );
  }

  /**
   * Sends a rejection email to the inviter when the invitee rejects the invitation.
   * @param data - An object containing the workspace ID, recipient's name, email, inviter's name, invitee's name, workspace name, and role name.
   */
  async sendRejectionEmailToInviter(data: SendRejectionEmailToInviter): Promise<void> {
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the workspaceInvitationRejectedInviterTemplate function.
    await this.sendMail(
      data.email,
      `${data.inviteeName} has rejected the invitation to ${data.workspaceName}`,
      workspaceInvitationRejectedInviterTemplate(
        data.inviteeName, // The name of the invitee, used in the email template to inform the inviter about who rejected the invitation.
        data.inviterName, // The name of the inviter, used in the email template to personalize the message and inform them about the rejection.
        data.workspaceName, // The name of the workspace, used in the email template to inform the inviter about which workspace the invitation was rejected for.
      ),
    );
  }

  /**
   * Sends a revocation email to the invitee when the inviter revokes the invitation.
   * @param data - An object containing the workspace ID, recipient's name, email, inviter's name, invitee's name, workspace name, and role name.
   */
  async sendRevocationEmailToInvitee(data: SendRevocationEmailToInvitee): Promise<void> {
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the workspaceInvitationRevokedInviteeTemplate function.
    await this.sendMail(
      data.email,
      `Your invitation to ${data.workspaceName} has been revoked`,
      workspaceInvitationRevokedInviteeTemplate(
        data.inviteeName, // The name of the invitee, used in the email template to personalize the message and inform them about the revocation.
        data.inviterName, // The name of the inviter, used in the email template to inform the invitee about who revoked the invitation.
        data.workspaceName, // The name of the workspace, used in the email template to inform the invitee about which workspace the invitation was revoked for.
      ),
    );
  }

  /**
   * Sends a user action email to the specified recipient, informing them about an action taken on their account.
   * @param data - An object containing the recipient's email, full name, action description, optional reason, and action time.
   */
  async sendUserActionEmail(data: UserActionTemplateProps): Promise<void> {
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the userActionTemplate function.
    await this.sendMail(
      data.email,
      `Your LinkFlow account has been updated: ${data.action}`,
      userActionTemplate(data), // The userActionTemplate function generates the HTML content of the email based on the provided data, including the recipient's full name, action description, optional reason, and action time.
    );
  }

  /**
   * Sends an ownership transferred email to the new owner of a workspace.
   * @param data - An object containing the recipient's email, name, and workspace name.
   */
  async sendOwnershipTransferredToNewOwner(
    data: SendOwnershipTransferredToNewOwner,
  ): Promise<void> {
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the workspaceOwnershipTransferredNewOwnerTemplate function.
    await this.sendMail(
      data.email,
      `You are now the owner of ${data.workspaceName}`,
      workspaceOwnershipTransferredNewOwnerTemplate(data.name, data.workspaceName), // The workspaceOwnershipTransferredNewOwnerTemplate function generates the HTML content of the email based on the provided data, including the recipient's name and the name of the workspace they now own.
    );
  }

  /**
   * Sends an ownership transferred email to the previous owner of a workspace.
   * @param data - An object containing the recipient's email, name, and workspace name.
   */
  async sendOwnershipTransferredToPreviousOwner(
    data: SendOwnershipTransferredToPreviousOwner,
  ): Promise<void> {
    // Use the sendMail method to send the email with the specified parameters, including the recipient's email, subject, and HTML content generated by the workspaceOwnershipTransferredPreviousOwnerTemplate function.
    await this.sendMail(
      data.email,
      `You are no longer the owner of ${data.workspaceName}`,
      workspaceOwnershipTransferredPreviousOwnerTemplate(data.name, data.workspaceName), // The workspaceOwnershipTransferredPreviousOwnerTemplate function generates the HTML content of the email based on the provided data, including the recipient's name and the name of the workspace they no longer own.
    );
  }

  /**
   * Sends an email to a workspace member when their role is updated.
   * @param data - An object containing the workspace ID, workspace name, member ID, user ID, member name, member email, previous role ID, previous role name, new role ID, new role name, updated at timestamp, and optional IP address.
   */
  async sendWorkspaceMemberRoleUpdatedEmail(
    data: SendWorkspaceMemberRoleUpdatedEmail,
  ): Promise<void> {
    await this.sendMail(
      data.memberEmail,
      `Your role in ${data.workspaceName} has been updated`,
      workspaceMemberRoleUpdatedTemplate(
        data.memberName, // The name of the member whose role has been updated, used in the email template to personalize the message.
        data.workspaceName, // The name of the workspace where the role update occurred, used in the email template to inform the member about the context of the change.
        data.previousRoleName, // The name of the member's previous role before the update, used in the email template to inform them about their former responsibilities.
        data.newRoleName, // The name of the member's new role after the update, used in the email template to inform them about their new responsibilities.
        `${config.CLIENT_URL}/workspaces/${data.slug}`, // A URL that directs the member to their workspace, constructed using the client URL and workspace slug, allowing them to easily access their workspace after the role change.
      ),
    );
  }

  /**
   * Sends an email to a workspace member when they leave the workspace.
   * @param data - An object containing the workspace ID, workspace name, owner name, member ID, member name, member email, role, leave at timestamp, and optional IP address.
   */
  async sendWorkspaceMemberLeaveEmail(data: WorkspaceMemberLeaveMail): Promise<void> {
    await this.sendMail(
      data.ownerEmail,
      `A member has left the workspace ${data.workspaceName}`,
      workspaceMemberLeftOwnerTemplate(
        data.ownerName, // The name of the owner of the workspace, used in the email template to inform the member about who is managing the workspace they have left.
        data.memberName, // The name of the member who has left the workspace, used in the email template to personalize the message.
        data.workspaceName, // The name of the workspace that the member has left, used in the email template to inform them about the context of their departure.
      ),
    );
  }

  /**
   * Sends an email to a workspace member when they are removed from the workspace.
   * @param data - An object containing the workspace ID, workspace name, user ID, member ID, member email, full name, role, optional delete at timestamp, and optional IP address.
   */
  async sendWorkspaceMemberRemovedEmail(data: WorkspaceMemberRemovedMail): Promise<void> {
    await this.sendMail(
      data.memberEmail,
      `You have been removed from the workspace ${data.workspaceName}`,
      workspaceMemberRemovedTemplate(
        data.fullName, // The full name of the member who has been removed from the workspace, used in the email template to personalize the message.
        data.workspaceName, // The name of the workspace from which the member has been removed, used in the email template to inform them about the context of their removal.
      ),
    );
  }

  /**
   * Sends an email to a workspace member when the workspace is deleted.
   * @param data - An object containing the workspace ID, member ID, member name, member email, workspace name, owner name, deleted at timestamp, and optional IP address.
   */
  async sendWorkspaceDeletedEmail(data: WorkspaceDeletedMail): Promise<void> {
    await this.sendMail(
      data.memberEmail,
      `The workspace ${data.workspaceName} has been deleted`,
      workspaceDeletedTemplate(
        data.memberName, // The name of the member who is receiving the email, used in the email template to personalize the message.
        data.workspaceName, // The name of the workspace that has been deleted, used in the email template to inform the member about the context of the deletion.
        data.ownerName, // The name of the owner who deleted the workspace, used in the email template to inform the member about who performed the deletion.
      ),
    );
  }

  /**
   * Sends an email using the configured SMTP transporter.
   * @param to - The recipient's email address.
   * @param subject - The subject of the email.
   * @param html - The HTML content of the email.
   */
  private async sendMail(to: string, subject: string, html: string) {
    // Use the transporter to send the email with the specified parameters, including the sender's address, recipient's address, subject, and HTML content.
    await this.transporter.sendMail({
      from: this.from, // The sender's email address, formatted with a display name and the configured SMTP_FROM address.
      to, // The recipient's email address, provided as a parameter to the sendMail method.
      subject, // The subject line of the email, provided as a parameter to the sendMail method.
      html, // The HTML content of the email, provided as a parameter to the sendMail method.
    });
  }
}
